name: Deploy to stage

on:
  push:
    branches:
      - stage
  pull_request:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: stage
      dir: ./infra/stage
    secrets: inherit